server:
  address: localhost
  port: 8000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/fullstackpersondb
    username: tahsin
    password: skyout123
    driver-class-name: com.mysql.cj.jdbc.Driver
